backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "data.js"
        label: "Products Data"
        name: "products"
        fields:
          - label: "ID"
            name: "id"
            widget: "string"
          - label: "Category"
            name: "category"
            widget: "select"
            options: ["perfume", "makeup", "handbag", "goldpolish", "sakha", "toys", "new"]
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Price"
            name: "price"
            widget: "string"
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Keywords"
            name: "keywords"
            widget: "list"
