backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"         # Used in CMS code
    label: "Products"        # Shown in the CMS UI
    file: "data.json"        # <-- Points to your JSON file
    fields:
      - label: "Products"
        name: "products"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "string" }
          - { label: "Category", name: "category", widget: "select", options: ["perfume", "makeup", "handbag", "goldpolish", "sakha", "toys", "new"] }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Price", name: "price", widget: "string" }
          - label: "Images"
            name: "images"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Keywords", name: "keywords", widget: "list" }
